### PR TITLE
add LikeArray and LikeObject attributes

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
The reason why even new attribute make the code more and more complex is that Asdf attributes is like small language extension. More generic and better approach is compiler-like algorithm, however it requires more efforts.

**Comment by yannick** [comment]
sorry forgot to review.
we should maybe add some examples into the docs.
about complexity: agree, we should probably stop adding more complex features

**Comment by 9il** [comment]
The are 2 big documentable unittests. Furthermore I would like to remove examples from the readme in in favor of auto-generated docs.

**Comment by yannick** [comment]
we need to move generate / move the table of valid attributes cheat-sheet into the docs.
problem is, that people usually don't look into the docs. the 5 minute problem.
if the top page of the docs contains all info thats fine, but currently http://docs.asdf.dlang.io/ is pretty much useless as a kickstart.

but independent of that problem i think the methods need a bit more verbose doc and reasoning. 
`Allows serilalize / deserialize fields like objects.` is just too concise of a comment imo.

**Pull request merged**
