### PR TITLE
update Asdf and add example

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by yannick** [comment]
looks good but last thing: can you add useful messages for whats wrong for all the `enforce` assertions.

**Comment by yannick** [comment]
if already possible enhance the example do produce a new json output looking like:
```json
{"fav_color": "red", "total_colors": 2}
```
fav_color: first color from the array
total_colors: length of the array

**Comment by 9il** [comment]
> if already possible enhance the example do produce a new json output looking like:
> 
> {"fav_color": "red", "total_colors": 2}
> fav_color: first color from the array
> total_colors: length of the array

Could you please describe the example with more details?

**Comment by yannick** [comment]
same as 
`jq '{"num_cols": .colors | length, "fav_color": .colors[1]}'`
would do.
-> picking out 1 value of array
-> counting length of array

**Pull request merged**
